### ISSUE TITLE
io.lesDatafil feiler

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/natursystem-lastejobb#2]
finnes ikke i referert lib

**Comment by steinho** [comment]
prøvde å bruke lestempjson i stedet - etter å rettet om 10+ plasser, men fikk trøbbel med :io.lesDatafil("na_grunntype_til_lkm.csv.json").items; i neste runde ...

**Comment by bjornreppen** [comment]
Prøvde å klone fra scratch + npm install + npm run build, fikk ingen feil.  Men det stemmer at lesDatafil kan ha blitt renamet til lesTempJson på et tidspunkt.  Kan det være at du hadde repoet lokalt fra før og ikke kjørte npm install etter å ha gjort git pull?  Dependencies uansett oppdatert nå.

**Comment by steinho** [comment]
Nei - 'ny pc' ... ,men det er mer som er trøbbel 
npm run download - går kjapt - men ingenting lastes ned.... 

kommer bare:
PS D:\Repos\natursystem-lastejobb> SET DEBUG=*
PS D:\Repos\natursystem-lastejobb> npm run download

> natursystem-lastejobb@1.0.0 download D:\Repos\natursystem-lastejobb
> node node_modules/lastejobb/index stages/download

ingen feilmeldinger

Kjører jeg download fila manuelt i vscode - kommer git repo ned i temp katalaogen

**Comment by steinho** [comment]
Måtte gjøre følgende endring for at stegenes skulle kunne kjøres:
![image](https://user-images.githubusercontent.com/3253353/95054402-28207480-06f2-11eb-95db-e0be34b463e0.png)

**Comment by steinho** [comment]
Og slik fortsetter det:
![image](https://user-images.githubusercontent.com/3253353/95054551-556d2280-06f2-11eb-9e63-8b64faed3f93.png)

Ser jeg har fått siste versjon av https://github.com/Artsdatabanken/lastejobb inn i node_modules... så alt skal være oppdatert

**Comment by steinho** [comment]
> Måtte gjøre følgende endring for at stegenes skulle kunne kjøres:
> ![image](https://user-images.githubusercontent.com/3253353/95054402-28207480-06f2-11eb-95db-e0be34b463e0.png)

Ser du bruker samme syntax på nye lastejobber : https://github.com/Artsdatabanken/maritim-grense-lastejobb/blob/master/package.json 

lastejob/index fungerer ikke her - kan ikke forstå at det har med at jeg kjører windows å gjøre  - prøver det samme på ubuntu - og feiler på de samme tingene der:
steinho@ADBHOEMM4800:~/natursystem-lastejobb$ npm run download

> natursystem-lastejobb@1.0.0 download /home/steinho/natursystem-lastejobb
> node node_modules/lastejobb/index stages/download

steinho@ADBHOEMM4800:~/natursystem-lastejobb$ ls
node_modules  package.json  package-lock.json  README.md  stages
